language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.10.3
services:
  - mongodb
env:
  global:
    - JIRA_CACHE_ENV=test
    - JIRA_CACHE_MONGODB_URI=mongodb://127.0.0.1:27017/jira_cache
